// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcCore_DbFirstApproach.Models;

#nullable disable

namespace MvcCore_DbFirstApproach.Migrations
{
    [DbContext(typeof(LpuDbContext))]
    partial class LpuDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MvcCore_DbFirstApproach.Models.Department", b =>
                {
                    b.Property<int>("DeptNo")
                        .HasColumnType("int");

                    b.Property<string>("Dname")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Location")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("NoOfEmp")
                        .HasColumnType("int")
                        .HasColumnName("No_of_Emp");

                    b.HasKey("DeptNo")
                        .HasName("PK__Departme__0148CAAED886853E");

                    b.ToTable("Department", (string)null);
                });

            modelBuilder.Entity("MvcCore_DbFirstApproach.Models.Employee", b =>
                {
                    b.Property<int>("EmpNo")
                        .HasColumnType("int");

                    b.Property<int?>("DeptNo")
                        .HasColumnType("int");

                    b.Property<string>("Ename")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("EName");

                    b.Property<int?>("Mgr")
                        .HasColumnType("int");

                    b.Property<int?>("Salary")
                        .HasColumnType("int");

                    b.HasKey("EmpNo")
                        .HasName("PK__Employee__AF2D66D3A6705BB5");

                    b.HasIndex("DeptNo");

                    b.ToTable("Employee", null, t =>
                        {
                            t.HasTrigger("trgDeleteEmp");

                            t.HasTrigger("trgInsertEmp");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("MvcCore_DbFirstApproach.Models.Employee", b =>
                {
                    b.HasOne("MvcCore_DbFirstApproach.Models.Department", "DeptNoNavigation")
                        .WithMany("Employees")
                        .HasForeignKey("DeptNo")
                        .HasConstraintName("FK__Employee__DeptNo__2B0A656D");

                    b.Navigation("DeptNoNavigation");
                });

            modelBuilder.Entity("MvcCore_DbFirstApproach.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
